[package]
name = "openai_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.29"
openai-api-stream-rs = "0.1.1"
tokio = { version = "1.34.0", features = ["full"] }
